[filetype]
rules = [
    # Regra para pastas (usando MIME type)
    { url = "*/", fg = "cyan", bold = true },
    # Fallback para o resto
    { name = "*", fg = "white" }
]

[mgr]
border_style = { fg = "darkgray" }

[mode]
normal_main = { bg = "reset", fg = "reset" }
normal_alt  = { bg = "reset", fg = "reset" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
