[mgr]
show_hidden = true

[opener]
edit = [
  { run = "vim \"$@\"", block = true, for = "unix" },
]
view = [
    { run = 'qimgv "$@"', orphan = true, desc = "Ver Imagem" },
]
play = [
    { run = 'mpv "$@"', orphan = true, desc = "Reproduzir m√≠dia" },
]
markdown = [
    { run = 'apostrophe "$@"', orphan = true, desc = "Editar no Apostrophe" },
]
pdf = [
  { run = 'zathura "$@"', desc = "Zathura", orphan = true }
]

[open]
rules = [
    # Se for imagem, use o opener 'view' que criamos acima
    { mime = "image/*", use = "view" },
    { mime = "video/*", use = "play" },
    { mime = "audio/*", use = "play" },
    { name = "*.md", use = "markdown" },
    { mime = "application/pdf", use = "pdf" }

]

[preview]
prepend_previewers = [
    { name = "*.md", run = "code" },
]

