[mgr]
show_hidden = true

[opener]
edit = [
  { run = "vim \"$@\"", block = true, for = "unix" },
]
view = [
    { run = 'qimgv "$@"', orphan = true, desc = "Ver Imagem" },
]
play = [
    { run = 'mpv "$@"', orphan = true, desc = "Reproduzir m√≠dia" },
]

[open]
rules = [
    # Se for imagem, use o opener 'view' que criamos acima
    { mime = "image/*", use = "view" },
    { mime = "video/*", use = "play" },
    { mime = "audio/*", use = "play" },
]

